name: Novas
version: '${project.version}'
main: de.vmzx.novas.Novas
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  novas:
    description: Main teil um alles zu verwalten RP
    usage: /<command> [add/remove <Spieler> <Betrag>]
    aliases: [nova]
permissions:
  Novas.add:
    description: wir können damit Nova's uns geben
    default: op
  Novas.remove:
    description: damit wir removen können Nova's
    default: op
  Novas.use:
    description: das anzeigen von unseren Nova's
    default: true
