name: Novas
version: '1.0.0'
main: de.vmzx.novas.Novas
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  epics:
    description: Main teil um alles zu verwalten RP
    usage: /<command> [add/remove <Spieler> <Betrag>]
    aliases: [epic]
permissions:
  Epics.add:
    description: wir können damit Nova's uns geben
    default: op
  Epics.remove:
    description: damit wir removen können Nova's
    default: op
  Epics.use:
    description: das anzeigen von unseren Nova's
    default: true
